---
name: FCGI-Async
version: 0.11
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: Module to allow use of FastCGI asynchronously
license: perl
requires:
  IO::Async::Buffer: 0.03
  IO::Async::Notifier: 0.03
build_requires:
  Test::More: 0
provides:
  FCGI::Async:
    file: lib/FCGI/Async.pm
    version: 0.11
  FCGI::Async::BuildParse:
    file: lib/FCGI/Async/BuildParse.pm
  FCGI::Async::ClientConnection:
    file: lib/FCGI/Async/ClientConnection.pm
  FCGI::Async::Constants:
    file: lib/FCGI/Async/Constants.pm
  FCGI::Async::Request:
    file: lib/FCGI/Async/Request.pm
generated_by: Module::Build version 0.26
