---
name: FCGI-Async
version: 0.07
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: Module to allow use of FastCGI asynchronously
license: perl
provides:
  FCGI::Async:
    file: lib/FCGI/Async.pm
    version: 0.07
  FCGI::Async::Constants:
    file: lib/FCGI/Async/Constants.pm
  FCGI::Async::Request:
    file: lib/FCGI/Async/Request.pm
generated_by: Module::Build version 0.26
